# Generated by Django 3.0.4 on 2020-04-05 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=30)),
                ('task', models.CharField(max_length=100)),
                ('startdate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('messagelogs', models.TextField(blank=True, null=True)),
                ('assignee', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('fstatus', models.BooleanField(default=False)),
            ],
        ),
    ]
